package com.example.firestar.model

import com.example.firestar.R

class Sky(val info:String,val icon:Int)

private val sky = mapOf(
    "100" to Sky("晴", R.drawable.ic_clear_day),
    "101" to Sky("多云", R.drawable.ic_partly_cloud_day),
    "102" to Sky("少云",R.drawable.ic_partly_cloud_day),
    "103" to Sky("晴转多云",R.drawable.ic_sunny_cloud_day),
    "104" to Sky("阴", R.drawable.ic_cloudy),
    "150" to Sky("晴", R.drawable.ic_clear_night),
    "151" to Sky("多云", R.drawable.ic_partly_cloud_night),
    "152" to Sky("少云", R.drawable.ic_partly_cloud_night),
    "153" to Sky("晴转多云",R.drawable.ic_sunny_cloud_night),
    "300" to Sky("阵雨",R.drawable.ic_shower_day),
    "301" to Sky("强阵雨",R.drawable.ic_shower_day),
    "302" to Sky("雷阵雨", R.drawable.ic_thunder_shower),
    "303" to Sky("强雷阵雨", R.drawable.ic_thunder_shower),
    "304" to Sky("雷阵雨伴有冰雹", R.drawable.ic_thunder_shower_hail),
    "305" to Sky("小雨", R.drawable.ic_light_rain),
    "306" to Sky("中雨", R.drawable.ic_moderate_rain),
    "307" to Sky("大雨", R.drawable.ic_heavy_rain),
    "308" to Sky("极端降雨", R.drawable.ic_extreme_rain),
    "309" to Sky("毛毛雨/细雨",R.drawable.ic_light_rain),
    "310" to Sky("暴雨",R.drawable.ic_storm_rain),
    "311" to Sky("大暴雨",R.drawable.ic_big_storm_rain),
    "312" to Sky("特大暴雨",R.drawable.ic_bigger_storm_rain),
    "313" to Sky("冻雨",R.drawable.ic_ice_rain),
    "314" to Sky("小到中雨",R.drawable.ic_small_mid_rain),
    "315" to Sky("中到大雨",R.drawable.ic_mid_big_rain),
    "316" to Sky("大到暴雨",R.drawable.ic_big_bigger_rain),
    "317" to Sky("暴雨到大暴雨",R.drawable.ic_storm_rain_one),
    "318" to Sky("大暴雨到特大暴雨",R.drawable.ic_storm_rain_two),
    "350" to Sky("阵雨",R.drawable.ic_shower_night),
    "351" to Sky("强阵雨",R.drawable.ic_shower_night),
    "399" to Sky("雨",R.drawable.ic_moderate_rain),
    "400" to Sky("小雪", R.drawable.ic_light_snow),
    "401" to Sky("中雪", R.drawable.ic_moderate_snow),
    "402" to Sky("大雪", R.drawable.ic_heavy_snow),
    "403" to Sky("暴雪", R.drawable.ic_heavy_snow),
    "404" to Sky("雨夹雪", R.drawable.ic_sleet),
    "405" to Sky("雨雪天气",R.drawable.ic_sleet),
    "406" to Sky("阵雨夹雪",R.drawable.ic_storm_rain_snow_day),
    "407" to Sky("阵雪",R.drawable.ic_snow_shower_day),
    "408" to Sky("小到中雪",R.drawable.ic_snow_small_mid),
    "409" to Sky("中到大雪",R.drawable.ic_snow_mid_big),
    "410" to Sky("大到暴雪",R.drawable.ic_snow_big_bigger),
    "456" to Sky("阵雨夹雪",R.drawable.ic_storm_rain_snow_night),
    "457" to Sky("阵雪",R.drawable.ic_snow_shower_night),
    "499" to Sky("雪",R.drawable.ic_moderate_snow),
    "500" to Sky("薄雾",R.drawable.ic_fog),
    "501" to Sky("雾",R.drawable.ic_fog),
    "502" to Sky("霾",R.drawable.ic_haze),
    "503" to Sky("扬沙",R.drawable.ic_jansha),
    "504" to Sky("浮尘",R.drawable.ic_dust),
    "507" to Sky("沙尘暴",R.drawable.ic_dust_storm),
    "508" to Sky("强沙尘暴",R.drawable.ic_strong_dust_storm),
    "509" to Sky("浓雾",R.drawable.ic_fog),
    "510" to Sky("强浓雾",R.drawable.ic_fog),
    "511" to Sky("中度霾",R.drawable.ic_haze),
    "512" to Sky("重度霾",R.drawable.ic_haze),
    "513" to Sky("严重霾",R.drawable.ic_haze),
    "514" to Sky("大雾",R.drawable.ic_fog),
    "515" to Sky("特强浓雾",R.drawable.ic_fog),
    "900" to Sky("热",R.drawable.ic_hot),
    "901" to Sky("冷",R.drawable.ic_cold),
    "999" to Sky("未知",R.drawable.ic_unknown_weather)
)

fun getSky(skycon: String): Sky {
    return sky[skycon] ?: sky["100"]!!
}